spring:
  application:
    name: ${SPRING_APPLICATION_NAME:dms}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:test} #WioVxwp&xII6UlMS7Ik1!ZU!u

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: ${SERVER_ERROR_INCLUDE_MESSAGE:always}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.ase.dms: ${LOGGING_LEVEL_COM_ASE_DMS:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
