spring:
  application:
    name: ${SPRING_APPLICATION_NAME:dms}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:testpassw}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.sau-portal.de/realms/sau
          jwk-set-uri: https://keycloak.sau-portal.de/realms/sau/protocol/openid-connect/certs
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /dms
  error:
    include-message: ${SERVER_ERROR_INCLUDE_MESSAGE:always}

# JodConverter / LibreOffice configuration
jodconverter:
  enabled: ${JODCONVERTER_ENABLED:true}
# office.home can also be set via system property -Doffice.home or env var OFFICE_HOME
office:
  home: ${office.home:${OFFICE_HOME:}}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.ase.dms: ${LOGGING_LEVEL_COM_ASE_DMS:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"

minio:
  endpoint: ${MINIO_ENDPOINT:localhost}
  port: ${MINIO_PORT:9000}
  tls: ${MINIO_TLS:false}
  access-key: ${MINIO_ACCESS_KEY:test}
  access-secret: ${MINIO_SECRET_KEY:testpassword}
  bucketName: ${MINIO_BUCKET_NAME:test}
