apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms-app
  namespace: ase-7
  labels:
    app: dms
    team: "7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dms
  template:
    metadata:
      labels:
        app: dms
        team: "7"
    spec:
      containers:
      - name: dms
        image: ghcr.io/agile-software-engineering-25/team-7-backend-dms-backend:latest
        ports:
        - containerPort: 8080
        env:
        # Database Configuration for Team 7
        - name: DB_HOST
          value: postgres.db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: appdb
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend
              key: POSTGRES_PASSWORD
        - name: SPRING_DATASOURCE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend
              key: POSTGRES_PASSWORD
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.postgresql.Driver"

        envFrom:
        - configMapRef:
            name: dms-backend-basic

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
