name: Checkstyle

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Ensure Checkstyle jar
        shell: bash
        run: |
          set -euo pipefail
          if [ -f checkstyle-11.0.0-all.jar ]; then
            echo "JAR=checkstyle-11.0.0-all.jar" >> "$GITHUB_ENV"
          elif [ -f checkstyle.jar ]; then
            echo "JAR=checkstyle.jar" >> "$GITHUB_ENV"
          else
            curl -sSL -o checkstyle-11.0.0-all.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-11.0.0/checkstyle-11.0.0-all.jar
            echo "JAR=checkstyle-11.0.0-all.jar" >> "$GITHUB_ENV"
          fi

      - name: Run Checkstyle
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p target
          STATUS=0
          java -jar "$JAR" -c checkstyle.xml -f xml -o target/checkstyle-report.xml src/main/java src/test/java || STATUS=$?
          # Print human-readable output to logs for convenience (do not fail this step anew)
          java -jar "$JAR" -c checkstyle.xml -f plain src/main/java src/test/java || true
          exit $STATUS

      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-report.xml


